version: '0.1.0'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gymbro-api
      POSTGRES_PASSWORD: 82KQ6KkyLo5
      POSTGRES_DB: gymbro
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
    networks:
      - host

volumes:
  postgresql:

networks:
  host:
    driver: bridge
